version: '2'
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: node
    container_name: vue
    # command: npm start
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    working_dir: /home/app
    volumes:
     - /home/${SUDO_USER}/studies/schoolOfNet/planoDeEstudo/vue:/home/app